### ISSUE TITLE
Enable Auto Apply button state not syncing correctly

### ISSUE THREAD

**Issue by FahadBinHussain** [numanzamandipuu/Notation#1]
Enable Auto Apply is already enabled but after refreshing the webpage it shows Enable Auto Apply as disabled. Where it should show the button as disabled
![image](https://user-images.githubusercontent.com/75292632/232802210-cc4c2d7f-552b-47ad-9550-26ed67965818.png)

**Comment by numanzamandipuu** [comment]
Thank you for bringing this issue to our attention. We apologize for any inconvenience caused. 

After investigating, we can confirm that the functionality of auto apply is working correctly even though the button text is not updating correctly after a refresh. 

When the button is initially enabled, it shows `Disable Auto Apply` as expected. But after refreshing the page, the button shows `Enable Auto Apply`, which is not expected even though the functionality of auto apply is still working correctly. 

Then if we click the button 2nd time after refreshing, it shows `Enable Auto Apply` and disables the auto apply functionality. If the button is clicked again, it enables auto apply and shows `Disable Auto Apply` as expected.

The main problem here is after refreshing, the first time the button shows `Enable Auto Apply` when it should be `Disable Auto Apply`.

We understand that this can be confusing, and we apologize for any frustration caused. We encourage you to take a closer look at the code and solve this bug. We appreciate your patience and understanding.

**Comment by FahadBinHussain** [comment]
I think the base problem is with the popup window. Because that doesn't work too the next time the extension is clicked. Even when the page is not refreshed.
